# Generated by Django 4.2.16 on 2025-05-26 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_amount',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='salary',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
