# Generated by Django 4.2.16 on 2025-05-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_products', '0001_initial'),
        ('accounts', '0004_user_current_amount_user_nickname_user_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='joined_saving_products',
            field=models.ManyToManyField(blank=True, to='fin_products.installmentsaving'),
        ),
        migrations.AddField(
            model_name='user',
            name='joined_term_products',
            field=models.ManyToManyField(blank=True, to='fin_products.termdeposit'),
        ),
    ]
