# Generated by Django 4.2.16 on 2025-05-27 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_joined_saving_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sub_product',
        ),
    ]
